#!/bin/bash -i

###Converted from AttractEasyModel by easy2model 1.1
### Generated by ATTRACT shell script generator version 0.5

set -u -e
if [ ! -f $ATTRACTDIR/../version ] ||  [ `awk '{print ($1 < 0.3)}' $ATTRACTDIR/../version` -eq 1 ]; then
  echo 'Your ATTRACT version is too old to run this protocol. Please download and install the latest version of ATTRACT'
  echo 'ATTRACT is available at: http://www.attract.ph.tum.de/services/ATTRACT/attract.tgz'
  exit 1
fi
trap "kill -- -$BASHPID; $ATTRACTDIR/shm-clean" ERR EXIT
$ATTRACTDIR/shm-clean

rm -rf result.dat result.pdb result.lrmsd result.irmsd result.fnat >& /dev/null

#name of the run
name=min_ens 

#docking parameters
params="$ATTRACTDIR/../attract.par partner1-ensemble/model-1r.pdb partner2-ensemble/model-1r.pdb --fix-receptor --ens 1 partner1-ensemble.list --ens 2 partner2-ensemble.list"
scoreparams="$ATTRACTDIR/../attract.par partner1-ensemble/model-1r.pdb partner2-ensemble/model-1r.pdb --score --fix-receptor --ens 1 partner1-ensemble.list --ens 2 partner2-ensemble.list"

#grid parameters
gridparams=" --grid 1 receptorgrid.gridheader"

#parallelization parameters
parals="--np 48 --chunks 48"
if [ 1 -eq 1 ]; then ### move and change to disable parts of the protocol

echo '**************************************************************'
echo 'Reduce partner PDBs...'
echo '**************************************************************'
rm -rf partner1-ensemble
mkdir partner1-ensemble
$ATTRACTTOOLS/splitmodel receptor.pdb partner1-ensemble/model 31 > /dev/null
cat /dev/null > partner1-ensemble.list
cat /dev/null > partner1-ensemble-aa.list
cat /dev/null > partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-1.pdb partner1-ensemble/model-1-aa.pdb --chain A --dumppatch --pdb2pqr > receptor.mapping
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-1-aa.pdb partner1-ensemble/model-1-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-1-aa.pdb partner1-ensemble/model-1r.pdb --chain A > /dev/null
echo partner1-ensemble/model-1r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-1-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-1-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-2.pdb partner1-ensemble/model-2-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-2-aa.pdb partner1-ensemble/model-2-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-2-aa.pdb partner1-ensemble/model-2r.pdb --chain A > /dev/null
echo partner1-ensemble/model-2r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-2-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-2-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-3.pdb partner1-ensemble/model-3-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-3-aa.pdb partner1-ensemble/model-3-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-3-aa.pdb partner1-ensemble/model-3r.pdb --chain A > /dev/null
echo partner1-ensemble/model-3r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-3-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-3-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-4.pdb partner1-ensemble/model-4-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-4-aa.pdb partner1-ensemble/model-4-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-4-aa.pdb partner1-ensemble/model-4r.pdb --chain A > /dev/null
echo partner1-ensemble/model-4r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-4-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-4-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-5.pdb partner1-ensemble/model-5-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-5-aa.pdb partner1-ensemble/model-5-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-5-aa.pdb partner1-ensemble/model-5r.pdb --chain A > /dev/null
echo partner1-ensemble/model-5r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-5-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-5-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-6.pdb partner1-ensemble/model-6-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-6-aa.pdb partner1-ensemble/model-6-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-6-aa.pdb partner1-ensemble/model-6r.pdb --chain A > /dev/null
echo partner1-ensemble/model-6r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-6-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-6-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-7.pdb partner1-ensemble/model-7-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-7-aa.pdb partner1-ensemble/model-7-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-7-aa.pdb partner1-ensemble/model-7r.pdb --chain A > /dev/null
echo partner1-ensemble/model-7r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-7-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-7-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-8.pdb partner1-ensemble/model-8-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-8-aa.pdb partner1-ensemble/model-8-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-8-aa.pdb partner1-ensemble/model-8r.pdb --chain A > /dev/null
echo partner1-ensemble/model-8r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-8-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-8-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-9.pdb partner1-ensemble/model-9-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-9-aa.pdb partner1-ensemble/model-9-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-9-aa.pdb partner1-ensemble/model-9r.pdb --chain A > /dev/null
echo partner1-ensemble/model-9r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-9-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-9-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-10.pdb partner1-ensemble/model-10-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-10-aa.pdb partner1-ensemble/model-10-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-10-aa.pdb partner1-ensemble/model-10r.pdb --chain A > /dev/null
echo partner1-ensemble/model-10r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-10-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-10-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-11.pdb partner1-ensemble/model-11-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-11-aa.pdb partner1-ensemble/model-11-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-11-aa.pdb partner1-ensemble/model-11r.pdb --chain A > /dev/null
echo partner1-ensemble/model-11r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-11-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-11-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-12.pdb partner1-ensemble/model-12-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-12-aa.pdb partner1-ensemble/model-12-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-12-aa.pdb partner1-ensemble/model-12r.pdb --chain A > /dev/null
echo partner1-ensemble/model-12r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-12-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-12-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-13.pdb partner1-ensemble/model-13-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-13-aa.pdb partner1-ensemble/model-13-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-13-aa.pdb partner1-ensemble/model-13r.pdb --chain A > /dev/null
echo partner1-ensemble/model-13r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-13-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-13-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-14.pdb partner1-ensemble/model-14-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-14-aa.pdb partner1-ensemble/model-14-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-14-aa.pdb partner1-ensemble/model-14r.pdb --chain A > /dev/null
echo partner1-ensemble/model-14r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-14-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-14-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-15.pdb partner1-ensemble/model-15-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-15-aa.pdb partner1-ensemble/model-15-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-15-aa.pdb partner1-ensemble/model-15r.pdb --chain A > /dev/null
echo partner1-ensemble/model-15r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-15-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-15-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-16.pdb partner1-ensemble/model-16-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-16-aa.pdb partner1-ensemble/model-16-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-16-aa.pdb partner1-ensemble/model-16r.pdb --chain A > /dev/null
echo partner1-ensemble/model-16r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-16-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-16-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-17.pdb partner1-ensemble/model-17-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-17-aa.pdb partner1-ensemble/model-17-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-17-aa.pdb partner1-ensemble/model-17r.pdb --chain A > /dev/null
echo partner1-ensemble/model-17r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-17-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-17-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-18.pdb partner1-ensemble/model-18-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-18-aa.pdb partner1-ensemble/model-18-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-18-aa.pdb partner1-ensemble/model-18r.pdb --chain A > /dev/null
echo partner1-ensemble/model-18r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-18-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-18-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-19.pdb partner1-ensemble/model-19-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-19-aa.pdb partner1-ensemble/model-19-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-19-aa.pdb partner1-ensemble/model-19r.pdb --chain A > /dev/null
echo partner1-ensemble/model-19r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-19-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-19-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-20.pdb partner1-ensemble/model-20-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-20-aa.pdb partner1-ensemble/model-20-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-20-aa.pdb partner1-ensemble/model-20r.pdb --chain A > /dev/null
echo partner1-ensemble/model-20r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-20-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-20-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-21.pdb partner1-ensemble/model-21-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-21-aa.pdb partner1-ensemble/model-21-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-21-aa.pdb partner1-ensemble/model-21r.pdb --chain A > /dev/null
echo partner1-ensemble/model-21r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-21-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-21-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-22.pdb partner1-ensemble/model-22-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-22-aa.pdb partner1-ensemble/model-22-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-22-aa.pdb partner1-ensemble/model-22r.pdb --chain A > /dev/null
echo partner1-ensemble/model-22r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-22-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-22-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-23.pdb partner1-ensemble/model-23-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-23-aa.pdb partner1-ensemble/model-23-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-23-aa.pdb partner1-ensemble/model-23r.pdb --chain A > /dev/null
echo partner1-ensemble/model-23r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-23-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-23-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-24.pdb partner1-ensemble/model-24-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-24-aa.pdb partner1-ensemble/model-24-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-24-aa.pdb partner1-ensemble/model-24r.pdb --chain A > /dev/null
echo partner1-ensemble/model-24r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-24-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-24-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-25.pdb partner1-ensemble/model-25-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-25-aa.pdb partner1-ensemble/model-25-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-25-aa.pdb partner1-ensemble/model-25r.pdb --chain A > /dev/null
echo partner1-ensemble/model-25r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-25-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-25-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-26.pdb partner1-ensemble/model-26-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-26-aa.pdb partner1-ensemble/model-26-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-26-aa.pdb partner1-ensemble/model-26r.pdb --chain A > /dev/null
echo partner1-ensemble/model-26r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-26-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-26-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-27.pdb partner1-ensemble/model-27-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-27-aa.pdb partner1-ensemble/model-27-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-27-aa.pdb partner1-ensemble/model-27r.pdb --chain A > /dev/null
echo partner1-ensemble/model-27r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-27-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-27-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-28.pdb partner1-ensemble/model-28-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-28-aa.pdb partner1-ensemble/model-28-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-28-aa.pdb partner1-ensemble/model-28r.pdb --chain A > /dev/null
echo partner1-ensemble/model-28r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-28-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-28-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-29.pdb partner1-ensemble/model-29-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-29-aa.pdb partner1-ensemble/model-29-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-29-aa.pdb partner1-ensemble/model-29r.pdb --chain A > /dev/null
echo partner1-ensemble/model-29r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-29-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-29-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-30.pdb partner1-ensemble/model-30-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-30-aa.pdb partner1-ensemble/model-30-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-30-aa.pdb partner1-ensemble/model-30r.pdb --chain A > /dev/null
echo partner1-ensemble/model-30r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-30-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-30-heavy.pdb >> partner1-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-31.pdb partner1-ensemble/model-31-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-31-aa.pdb partner1-ensemble/model-31-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner1-ensemble/model-31-aa.pdb partner1-ensemble/model-31r.pdb --chain A > /dev/null
echo partner1-ensemble/model-31r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-31-aa.pdb >> partner1-ensemble-aa.list
echo partner1-ensemble/model-31-heavy.pdb >> partner1-ensemble-aa-rmsd.list
rm -rf partner2-ensemble
mkdir partner2-ensemble
$ATTRACTTOOLS/splitmodel ligand.pdb partner2-ensemble/model 31 > /dev/null
cat /dev/null > partner2-ensemble.list
cat /dev/null > partner2-ensemble-aa.list
cat /dev/null > partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-1.pdb partner2-ensemble/model-1-aa.pdb --chain B --dumppatch --pdb2pqr > ligand.mapping
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-1-aa.pdb partner2-ensemble/model-1-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-1-aa.pdb partner2-ensemble/model-1r.pdb --chain B > /dev/null
echo partner2-ensemble/model-1r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-1-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-1-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-2.pdb partner2-ensemble/model-2-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-2-aa.pdb partner2-ensemble/model-2-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-2-aa.pdb partner2-ensemble/model-2r.pdb --chain B > /dev/null
echo partner2-ensemble/model-2r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-2-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-2-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-3.pdb partner2-ensemble/model-3-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-3-aa.pdb partner2-ensemble/model-3-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-3-aa.pdb partner2-ensemble/model-3r.pdb --chain B > /dev/null
echo partner2-ensemble/model-3r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-3-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-3-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-4.pdb partner2-ensemble/model-4-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-4-aa.pdb partner2-ensemble/model-4-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-4-aa.pdb partner2-ensemble/model-4r.pdb --chain B > /dev/null
echo partner2-ensemble/model-4r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-4-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-4-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-5.pdb partner2-ensemble/model-5-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-5-aa.pdb partner2-ensemble/model-5-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-5-aa.pdb partner2-ensemble/model-5r.pdb --chain B > /dev/null
echo partner2-ensemble/model-5r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-5-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-5-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-6.pdb partner2-ensemble/model-6-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-6-aa.pdb partner2-ensemble/model-6-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-6-aa.pdb partner2-ensemble/model-6r.pdb --chain B > /dev/null
echo partner2-ensemble/model-6r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-6-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-6-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-7.pdb partner2-ensemble/model-7-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-7-aa.pdb partner2-ensemble/model-7-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-7-aa.pdb partner2-ensemble/model-7r.pdb --chain B > /dev/null
echo partner2-ensemble/model-7r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-7-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-7-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-8.pdb partner2-ensemble/model-8-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-8-aa.pdb partner2-ensemble/model-8-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-8-aa.pdb partner2-ensemble/model-8r.pdb --chain B > /dev/null
echo partner2-ensemble/model-8r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-8-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-8-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-9.pdb partner2-ensemble/model-9-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-9-aa.pdb partner2-ensemble/model-9-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-9-aa.pdb partner2-ensemble/model-9r.pdb --chain B > /dev/null
echo partner2-ensemble/model-9r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-9-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-9-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-10.pdb partner2-ensemble/model-10-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-10-aa.pdb partner2-ensemble/model-10-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-10-aa.pdb partner2-ensemble/model-10r.pdb --chain B > /dev/null
echo partner2-ensemble/model-10r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-10-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-10-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-11.pdb partner2-ensemble/model-11-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-11-aa.pdb partner2-ensemble/model-11-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-11-aa.pdb partner2-ensemble/model-11r.pdb --chain B > /dev/null
echo partner2-ensemble/model-11r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-11-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-11-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-12.pdb partner2-ensemble/model-12-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-12-aa.pdb partner2-ensemble/model-12-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-12-aa.pdb partner2-ensemble/model-12r.pdb --chain B > /dev/null
echo partner2-ensemble/model-12r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-12-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-12-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-13.pdb partner2-ensemble/model-13-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-13-aa.pdb partner2-ensemble/model-13-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-13-aa.pdb partner2-ensemble/model-13r.pdb --chain B > /dev/null
echo partner2-ensemble/model-13r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-13-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-13-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-14.pdb partner2-ensemble/model-14-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-14-aa.pdb partner2-ensemble/model-14-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-14-aa.pdb partner2-ensemble/model-14r.pdb --chain B > /dev/null
echo partner2-ensemble/model-14r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-14-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-14-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-15.pdb partner2-ensemble/model-15-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-15-aa.pdb partner2-ensemble/model-15-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-15-aa.pdb partner2-ensemble/model-15r.pdb --chain B > /dev/null
echo partner2-ensemble/model-15r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-15-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-15-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-16.pdb partner2-ensemble/model-16-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-16-aa.pdb partner2-ensemble/model-16-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-16-aa.pdb partner2-ensemble/model-16r.pdb --chain B > /dev/null
echo partner2-ensemble/model-16r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-16-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-16-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-17.pdb partner2-ensemble/model-17-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-17-aa.pdb partner2-ensemble/model-17-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-17-aa.pdb partner2-ensemble/model-17r.pdb --chain B > /dev/null
echo partner2-ensemble/model-17r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-17-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-17-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-18.pdb partner2-ensemble/model-18-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-18-aa.pdb partner2-ensemble/model-18-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-18-aa.pdb partner2-ensemble/model-18r.pdb --chain B > /dev/null
echo partner2-ensemble/model-18r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-18-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-18-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-19.pdb partner2-ensemble/model-19-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-19-aa.pdb partner2-ensemble/model-19-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-19-aa.pdb partner2-ensemble/model-19r.pdb --chain B > /dev/null
echo partner2-ensemble/model-19r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-19-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-19-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-20.pdb partner2-ensemble/model-20-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-20-aa.pdb partner2-ensemble/model-20-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-20-aa.pdb partner2-ensemble/model-20r.pdb --chain B > /dev/null
echo partner2-ensemble/model-20r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-20-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-20-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-21.pdb partner2-ensemble/model-21-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-21-aa.pdb partner2-ensemble/model-21-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-21-aa.pdb partner2-ensemble/model-21r.pdb --chain B > /dev/null
echo partner2-ensemble/model-21r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-21-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-21-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-22.pdb partner2-ensemble/model-22-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-22-aa.pdb partner2-ensemble/model-22-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-22-aa.pdb partner2-ensemble/model-22r.pdb --chain B > /dev/null
echo partner2-ensemble/model-22r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-22-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-22-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-23.pdb partner2-ensemble/model-23-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-23-aa.pdb partner2-ensemble/model-23-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-23-aa.pdb partner2-ensemble/model-23r.pdb --chain B > /dev/null
echo partner2-ensemble/model-23r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-23-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-23-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-24.pdb partner2-ensemble/model-24-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-24-aa.pdb partner2-ensemble/model-24-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-24-aa.pdb partner2-ensemble/model-24r.pdb --chain B > /dev/null
echo partner2-ensemble/model-24r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-24-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-24-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-25.pdb partner2-ensemble/model-25-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-25-aa.pdb partner2-ensemble/model-25-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-25-aa.pdb partner2-ensemble/model-25r.pdb --chain B > /dev/null
echo partner2-ensemble/model-25r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-25-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-25-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-26.pdb partner2-ensemble/model-26-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-26-aa.pdb partner2-ensemble/model-26-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-26-aa.pdb partner2-ensemble/model-26r.pdb --chain B > /dev/null
echo partner2-ensemble/model-26r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-26-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-26-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-27.pdb partner2-ensemble/model-27-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-27-aa.pdb partner2-ensemble/model-27-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-27-aa.pdb partner2-ensemble/model-27r.pdb --chain B > /dev/null
echo partner2-ensemble/model-27r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-27-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-27-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-28.pdb partner2-ensemble/model-28-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-28-aa.pdb partner2-ensemble/model-28-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-28-aa.pdb partner2-ensemble/model-28r.pdb --chain B > /dev/null
echo partner2-ensemble/model-28r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-28-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-28-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-29.pdb partner2-ensemble/model-29-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-29-aa.pdb partner2-ensemble/model-29-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-29-aa.pdb partner2-ensemble/model-29r.pdb --chain B > /dev/null
echo partner2-ensemble/model-29r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-29-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-29-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-30.pdb partner2-ensemble/model-30-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-30-aa.pdb partner2-ensemble/model-30-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-30-aa.pdb partner2-ensemble/model-30r.pdb --chain B > /dev/null
echo partner2-ensemble/model-30r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-30-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-30-heavy.pdb >> partner2-ensemble-aa-rmsd.list
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-31.pdb partner2-ensemble/model-31-aa.pdb --chain B --dumppatch --reference partner2-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py partner2-ensemble/model-31-aa.pdb partner2-ensemble/model-31-heavy.pdb --heavy  --readpatch  > /dev/null
python $ATTRACTTOOLS/reduce.py partner2-ensemble/model-31-aa.pdb partner2-ensemble/model-31r.pdb --chain B > /dev/null
echo partner2-ensemble/model-31r.pdb >> partner2-ensemble.list
echo partner2-ensemble/model-31-aa.pdb >> partner2-ensemble-aa.list
echo partner2-ensemble/model-31-heavy.pdb >> partner2-ensemble-aa-rmsd.list

echo '**************************************************************'
echo 'Reduce reference PDBs...'
echo '**************************************************************'
python $ATTRACTDIR/../allatom/aareduce.py receptor-rmsd.pdb refe-rmsd-1.pdb --heavy --pdb2pqr > /dev/null
python $ATTRACTDIR/../allatom/aareduce.py ligand-rmsd.pdb refe-rmsd-2.pdb --heavy --pdb2pqr > /dev/null

fi
if [ 1 -eq 0 ]; then

echo '**************************************************************'
echo 'Generate starting structures...'
echo '**************************************************************'
cat $ATTRACTDIR/../rotation.dat > rotation.dat
$ATTRACTDIR/translate partner1-ensemble/model-1r.pdb partner2-ensemble/model-1r.pdb > translate.dat
$ATTRACTDIR/systsearch > systsearch.dat
start=systsearch.dat

echo '**************************************************************'
echo 'ensemble search:' 
echo ' add ensemble conformations to the starting structures'
echo '**************************************************************'

echo '**************************************************************'
echo 'random ensemble conformation in ligand 1 for each starting structure'
echo '**************************************************************'
python $ATTRACTTOOLS/ensemblize.py systsearch.dat 31 1 random  > systsearch-ens1.dat

echo '**************************************************************'
echo 'random ensemble conformation in ligand 2 for each starting structure'
echo '**************************************************************'
python $ATTRACTTOOLS/ensemblize.py systsearch-ens1.dat 31 2 random  > systsearch-ens1-ens2.dat

echo '**************************************************************'
echo 'calculate receptorgrid grid'
echo '**************************************************************'
awk '{print substr($0,58,2)}' partner2-ensemble/model-1r.pdb | sort -nu > receptorgrid.alphabet
$ATTRACTDIR/make-grid-omp partner1-ensemble/model-1r.pdb $ATTRACTDIR/../attract.par 10.0 12.0 receptorgrid.gridheader  --shm --alphabet receptorgrid.alphabet

echo '**************************************************************'
echo 'Docking'
echo '**************************************************************'

echo '**************************************************************'
echo '1st minimization'
echo '**************************************************************'
python $ATTRACTDIR/../protocols/attract.py systsearch-ens1-ens2.dat $params $gridparams --vmax 1000 $parals --output out_$name.dat

echo '**************************************************************'
echo 'Final rescoring'
echo '**************************************************************'
python $ATTRACTDIR/../protocols/attract.py out_$name.dat $scoreparams --rcut 50.0 $parals --output out_$name.score
     
echo '**************************************************************'
echo 'Merge the scores with the structures'
echo '**************************************************************'
#python $ATTRACTTOOLS/fill-energies.py out_$name.dat out_$name.score > out_$name-scored.dat

echo '**************************************************************'
echo 'Sort structures'
echo '**************************************************************'
#python $ATTRACTTOOLS/sort.py out_$name-scored.dat > out_$name-sorted.dat

echo '**************************************************************'
echo 'Remove redundant structures'
echo '**************************************************************'
#$ATTRACTDIR/deredundant out_$name-sorted.dat 2 --ens 31 31 | python $ATTRACTTOOLS/fill-deredundant.py /dev/stdin out_$name-sorted.dat > out_$name-sorted-dr.dat

echo '**************************************************************'
echo 'Soft-link the final results'
echo '**************************************************************'
#ln -s out_$name-sorted-dr.dat result.dat

echo '**************************************************************'
echo 'collect top 1 structures:'
echo '**************************************************************'
#$ATTRACTTOOLS/top out_$name-sorted-dr.dat 1 > out_$name-top1.dat
#$ATTRACTDIR/collect out_$name-top1.dat partner1-ensemble/model-1-aa.pdb partner2-ensemble/model-1-aa.pdb --ens 1 partner1-ensemble-aa.list --ens 2 partner2-ensemble-aa.list > out_$name-top1.pdb
#ln -s out_$name-top1.pdb result.pdb

echo '**************************************************************'
echo 'calculate backbone ligand RMSD'
echo '**************************************************************'
python $ATTRACTDIR/lrmsd.py out_$name.dat partner2-ensemble/model-1-aa.pdb ligand-rmsd.pdb --ens 1 partner1-ensemble-aa.list --ens 2 partner2-ensemble-aa.list --receptor partner1-ensemble/model-1-aa.pdb > out_$name.lrmsd
ln -s out_$name.lrmsd result.lrmsd

echo '**************************************************************'
echo 'calculate backbone interface RMSD'
echo '**************************************************************'
python $ATTRACTDIR/irmsd.py out_$name.dat partner1-ensemble/model-1-heavy.pdb refe-rmsd-1.pdb partner2-ensemble/model-1-heavy.pdb refe-rmsd-2.pdb --ens 1 partner1-ensemble-aa-rmsd.list --ens 2 partner2-ensemble-aa-rmsd.list  > out_$name.irmsd
ln -s out_$name.irmsd result.irmsd

echo '**************************************************************'
echo 'calculate fraction of native contacts'
echo '**************************************************************'
python $ATTRACTDIR/fnat.py out_$name.dat 5 partner1-ensemble/model-1-heavy.pdb refe-rmsd-1.pdb partner2-ensemble/model-1-heavy.pdb refe-rmsd-2.pdb --ens 1 partner1-ensemble-aa-rmsd.list --ens 2 partner2-ensemble-aa-rmsd.list > out_$name.fnat
ln -s out_$name.fnat result.fnat

$ATTRACTDIR/shm-clean

fi ### move to disable parts of the protocol
